apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    run: my-notes-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: my-notes-app
